In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_train=pd.read_csv(r"C:\Users\khush\Downloads\train_Hr.csv")
data_train

employee_id         department     region         education gender  \
0            65438  Sales & Marketing   region_7  Master's & above      f   
1            65141         Operations  region_22        Bachelor's      m   
2             7513  Sales & Marketing  region_19        Bachelor's      m   
3             2542  Sales & Marketing  region_23        Bachelor's      m   
4            48945         Technology  region_26        Bachelor's      m   
...            ...                ...        ...               ...    ...   
54803         3030         Technology  region_14        Bachelor's      m   
54804        74592         Operations  region_27  Master's & above      f   
54805        13918          Analytics   region_1        Bachelor's      m   
54806        13614  Sales & Marketing   region_9               NaN      m   
54807        51526                 HR  region_22        Bachelor's      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                   5.0   
1                   other                1   30                   5.0   
2                sourcing                1   34                   3.0   
3                   other                2   39                   1.0   
4                   other                1   45                   3.0   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                   3.0   
54804               other                1   37                   2.0   
54805               other                1   27                   5.0   
54806            sourcing                1   29                   1.0   
54807               other                1   27                   1.0   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                      8              1            0                  49   
1                      4              0            0                  60   
2                      7              0            0                  50   
3                     10              0            0                  50   
4                      2              0            0                  73   
...                  ...            ...          ...                 ...   
54803                 17              0            0                  78   
54804                  6              0            0                  56   
54805                  3              1            0                  79   
54806                  2              0            0                  45   
54807                  5              0            0                  49   

       is_promoted  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
54803            0  
54804            0  
54805            0  
54806            0  
54807            0  

[54808 rows x 14 columns]

In [3]:
data_train=data_train.drop(["employee_id"],axis=1)
data_train

department     region         education gender  \
0      Sales & Marketing   region_7  Master's & above      f   
1             Operations  region_22        Bachelor's      m   
2      Sales & Marketing  region_19        Bachelor's      m   
3      Sales & Marketing  region_23        Bachelor's      m   
4             Technology  region_26        Bachelor's      m   
...                  ...        ...               ...    ...   
54803         Technology  region_14        Bachelor's      m   
54804         Operations  region_27  Master's & above      f   
54805          Analytics   region_1        Bachelor's      m   
54806  Sales & Marketing   region_9               NaN      m   
54807                 HR  region_22        Bachelor's      m   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   35                   5.0   
1                   other                1   30                   5.0   
2                sourcing                1   34                   3.0   
3                   other                2   39                   1.0   
4                   other                1   45                   3.0   
...                   ...              ...  ...                   ...   
54803            sourcing                1   48                   3.0   
54804               other                1   37                   2.0   
54805               other                1   27                   5.0   
54806            sourcing                1   29                   1.0   
54807               other                1   27                   1.0   

       length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                      8              1            0                  49   
1                      4              0            0                  60   
2                      7              0            0                  50   
3                     10              0            0                  50   
4                      2              0            0                  73   
...                  ...            ...          ...                 ...   
54803                 17              0            0                  78   
54804                  6              0            0                  56   
54805                  3              1            0                  79   
54806                  2              0            0                  45   
54807                  5              0            0                  49   

       is_promoted  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
54803            0  
54804            0  
54805            0  
54806            0  
54807            0  

[54808 rows x 13 columns]

In [4]:
data_train=data_train.rename(columns={"awards_won?":"awardswon"})

In [5]:
data_train.isnull().sum()

department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awardswon                  0
avg_training_score         0
is_promoted                0
dtype: int64

In [6]:
data_train.education=data_train.education.fillna("Below Secondary")
data_train.previous_year_rating=data_train.previous_year_rating.fillna(2.0)

In [7]:
data_train.isnull().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awardswon               0
avg_training_score      0
is_promoted             0
dtype: int64

In [8]:
data_train.dtypes

department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awardswon                 int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [10]:
data_train.department=le.fit_transform(data_train.department)
data_train.region=le.fit_transform(data_train.region)
data_train.education=le.fit_transform(data_train.education)
data_train.gender=le.fit_transform(data_train.gender)
data_train.recruitment_channel=le.fit_transform(data_train.recruitment_channel)

In [11]:
data_train.dtypes

department                int32
region                    int32
education                 int32
gender                    int32
recruitment_channel       int32
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awardswon                 int64
avg_training_score        int64
is_promoted               int64
dtype: object

In [12]:
data_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

# Random undersampling

In [13]:
data_train.is_promoted.value_counts()#imbalance data

0    50140
1     4668
Name: is_promoted, dtype: int64

In [14]:
c_0,c_1=data_train["is_promoted"].value_counts()
c_0,c_1

(50140, 4668)

In [15]:
train_0=data_train[data_train["is_promoted"]==0]
train_1=data_train[data_train["is_promoted"]==1]
train_0.shape,train_1.shape

((50140, 13), (4668, 13))

In [16]:
#train_1.head(2)

In [17]:
class_0under=train_0.sample(c_1)

In [18]:
class_0under.shape,train_1.shape

((4668, 13), (4668, 13))

In [19]:
class0_1=pd.concat([class_0under,train_1],axis=0)
class0_1.head()
class0_1.shape

(9336, 13)

In [20]:
class0_1.is_promoted.value_counts()

0    4668
1    4668
Name: is_promoted, dtype: int64

In [21]:
x=class0_1.iloc[:,0:-1]
y=class0_1.iloc[:,-1]

In [22]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.2,random_state=100)

In [23]:
xtr.shape,xte.shape,ytr.shape,yte.shape

((7468, 12), (1868, 12), (7468,), (1868,))

# Logistic Regression-Random Undersampling

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# LogisticRegression

In [25]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [26]:
lg.fit(xtr,ytr)

LogisticRegression()

In [27]:
p1=lg.predict(xte)
p1

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [28]:
prob=lg.predict_proba(xte)

In [29]:
df=pd.DataFrame(prob)
df

0         1
0     0.816141  0.183859
1     0.516378  0.483622
2     0.771646  0.228354
3     0.640233  0.359767
4     0.830387  0.169613
...        ...       ...
1863  0.437057  0.562943
1864  0.607106  0.392894
1865  0.416052  0.583948
1866  0.462119  0.537881
1867  0.110230  0.889770

[1868 rows x 2 columns]

In [30]:
from sklearn.metrics import confusion_matrix
cf1=confusion_matrix(yte,p1)
cf1

array([[660, 281],
       [245, 682]], dtype=int64)

In [31]:
ac1=cf1.diagonal().sum()/cf1.sum()*100
ac1

71.84154175588866

In [32]:
print(classification_report(yte,p1)) 

              precision    recall  f1-score   support

           0       0.73      0.70      0.72       941
           1       0.71      0.74      0.72       927

    accuracy                           0.72      1868
   macro avg       0.72      0.72      0.72      1868
weighted avg       0.72      0.72      0.72      1868



# Random Forest

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [34]:
rf.fit(xtr,ytr)

RandomForestClassifier()

In [35]:
rf_p=rf.predict(xte)

In [36]:
rf_c=confusion_matrix(yte,rf_p)
rf_c

array([[685, 256],
       [121, 806]], dtype=int64)

In [37]:
rf_ac=rf_c.diagonal().sum()/rf_c.sum()*100
rf_ac

79.81798715203426

In [38]:
print(classification_report(yte,rf_p))

              precision    recall  f1-score   support

           0       0.85      0.73      0.78       941
           1       0.76      0.87      0.81       927

    accuracy                           0.80      1868
   macro avg       0.80      0.80      0.80      1868
weighted avg       0.80      0.80      0.80      1868



# KNN

In [39]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [40]:
knn.fit(xtr,ytr)

KNeighborsClassifier()

In [41]:
knn_p=knn.predict(xte)

In [42]:
knn_c1=confusion_matrix(yte,knn_p)
knn_c1

array([[651, 290],
       [360, 567]], dtype=int64)

In [43]:
knn_ac1=knn_c1.diagonal().sum()/knn_c1.sum()*100
knn_ac1

65.20342612419701

In [44]:
print(classification_report(yte,knn_p))

              precision    recall  f1-score   support

           0       0.64      0.69      0.67       941
           1       0.66      0.61      0.64       927

    accuracy                           0.65      1868
   macro avg       0.65      0.65      0.65      1868
weighted avg       0.65      0.65      0.65      1868



# XGB

In [45]:
import xgboost
from xgboost import XGBClassifier

In [46]:
xgb=XGBClassifier()

In [47]:
xgb.fit(xtr,ytr)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [48]:
xgb_p=xgb.predict(xte)

In [49]:
xgb_c=confusion_matrix(yte,xgb_p)
xgb_c

array([[721, 220],
       [137, 790]], dtype=int64)

In [50]:
xgb_ac=xgb_c.diagonal().sum()/xgb_c.sum()*100
xgb_ac

80.88865096359743

In [51]:
print(classification_report(yte,xgb_p))

              precision    recall  f1-score   support

           0       0.84      0.77      0.80       941
           1       0.78      0.85      0.82       927

    accuracy                           0.81      1868
   macro avg       0.81      0.81      0.81      1868
weighted avg       0.81      0.81      0.81      1868



# DT-Random Undersampling

In [52]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [53]:
dt.fit(xtr,ytr)

DecisionTreeClassifier()

In [54]:
dt_p=dt.predict(xte)

In [55]:
c2=confusion_matrix(yte,dt_p)
c2

array([[728, 213],
       [236, 691]], dtype=int64)

In [56]:
a2=c2.diagonal().sum()/c2.sum()*100
a2

75.96359743040685

In [57]:
print(classification_report(yte,dt_p))

              precision    recall  f1-score   support

           0       0.76      0.77      0.76       941
           1       0.76      0.75      0.75       927

    accuracy                           0.76      1868
   macro avg       0.76      0.76      0.76      1868
weighted avg       0.76      0.76      0.76      1868



# SVM

In [58]:
from sklearn.svm import SVC
svm=SVC()

In [59]:
svm.fit(xtr,ytr)

SVC()

In [60]:
svm_p=svm.predict(xte)

In [61]:
svm_cf=confusion_matrix(yte,svm_p)
svm_cf

array([[649, 292],
       [387, 540]], dtype=int64)

In [62]:
svm_ac=svm_cf.diagonal().sum()/svm_cf.sum()*100
svm_ac

63.65096359743041

In [63]:
print(classification_report(yte,svm_p))

              precision    recall  f1-score   support

           0       0.63      0.69      0.66       941
           1       0.65      0.58      0.61       927

    accuracy                           0.64      1868
   macro avg       0.64      0.64      0.64      1868
weighted avg       0.64      0.64      0.64      1868



# Naive Bayes

In [64]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [65]:
nb.fit(xtr,ytr)

MultinomialNB()

In [66]:
nb_p=nb.predict(xte)

In [67]:
nb_cf=confusion_matrix(yte,nb_p)
nb_cf

array([[574, 367],
       [346, 581]], dtype=int64)

In [68]:
nb_acc=nb_cf.diagonal().sum()/nb_cf.sum()*100
nb_acc

61.83083511777302

In [69]:
print(classification_report(yte,nb_p))

              precision    recall  f1-score   support

           0       0.62      0.61      0.62       941
           1       0.61      0.63      0.62       927

    accuracy                           0.62      1868
   macro avg       0.62      0.62      0.62      1868
weighted avg       0.62      0.62      0.62      1868



In [70]:
#Conclusion : We get the best accuracy for: RF=79.12 and XGBOOST =79.99 then we see the confusion matix and we find that XGBOOST is best fitted model for this.

# Random Oversampling

In [71]:
c_0,c_1

(50140, 4668)

In [72]:
class_1over=train_1.sample(c_0,replace=True)

In [73]:
#class_1over.head()
class_1over.shape,train_0.shape

((50140, 13), (50140, 13))

In [74]:
class1_0=pd.concat([class_1over,train_0],axis=0)
class1_0.shape

(100280, 13)

In [75]:
class1_0.is_promoted.value_counts()

1    50140
0    50140
Name: is_promoted, dtype: int64

In [76]:
x1=class1_0.iloc[:,0:-1]
y1=class1_0.iloc[:,-1]

In [77]:
from sklearn.model_selection import train_test_split
xtr1,xte1,ytr1,yte1=train_test_split(x1,y1,test_size=0.2,random_state=100)

In [78]:

xtr1.shape,xte1.shape,ytr1.shape,yte1.shape

((80224, 12), (20056, 12), (80224,), (20056,))

# Logistic Regression- Random Oversampling

In [79]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [80]:
lg.fit(xtr1,ytr1)

LogisticRegression()

In [81]:
p1=lg.predict(xte1)
p1

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [82]:
prob=lg.predict_proba(xte1)

In [83]:
df=pd.DataFrame(prob)
df

0         1
0      0.185281  0.814719
1      0.243205  0.756795
2      0.700200  0.299800
3      0.049225  0.950775
4      0.461938  0.538062
...         ...       ...
20051  0.777099  0.222901
20052  0.435094  0.564906
20053  0.297091  0.702909
20054  0.677790  0.322210
20055  0.315727  0.684273

[20056 rows x 2 columns]

In [84]:
from sklearn.metrics import confusion_matrix
cf1=confusion_matrix(yte1,p1)
cf1

array([[6949, 3052],
       [2430, 7625]], dtype=int64)

In [85]:
ac1=cf1.diagonal().sum()/cf1.sum()*100
ac1

72.66653370562425

In [86]:
from sklearn.metrics import classification_report

In [87]:
print(classification_report(yte1,p1))

              precision    recall  f1-score   support

           0       0.74      0.69      0.72     10001
           1       0.71      0.76      0.74     10055

    accuracy                           0.73     20056
   macro avg       0.73      0.73      0.73     20056
weighted avg       0.73      0.73      0.73     20056



# Decision Tree

In [88]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [89]:
dt.fit(xtr1,ytr1)

DecisionTreeClassifier()

In [90]:
dt_p=dt.predict(xte1)
dt_p

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [91]:
dt_c=confusion_matrix(yte1,dt_p)
dt_c

array([[ 9366,   635],
       [    0, 10055]], dtype=int64)

In [92]:
dt_ac=dt_c.diagonal().sum()/dt_c.sum()*100
dt_ac

96.83386517750299

In [93]:
print(classification_report(yte1,dt_p))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97     10001
           1       0.94      1.00      0.97     10055

    accuracy                           0.97     20056
   macro avg       0.97      0.97      0.97     20056
weighted avg       0.97      0.97      0.97     20056



# Random Forest

In [94]:
rf.fit(xtr1,ytr1)

RandomForestClassifier()

In [95]:
rf_p=rf.predict(xte1)

In [96]:
rf_c=confusion_matrix(yte1,rf_p)
rf_c

array([[ 9753,   248],
       [    0, 10055]], dtype=int64)

In [97]:
rf_ac=rf_c.diagonal().sum()/rf_c.sum()*100
rf_ac

98.76346230554448

In [98]:
print(classification_report(yte1,rf_p))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     10001
           1       0.98      1.00      0.99     10055

    accuracy                           0.99     20056
   macro avg       0.99      0.99      0.99     20056
weighted avg       0.99      0.99      0.99     20056



# KNN

In [99]:
knn.fit(xtr1,ytr1)

KNeighborsClassifier()

In [100]:
knn_p=knn.predict(xte1)

In [101]:
knn_c1=confusion_matrix(yte1,knn_p)
knn_c1

array([[ 8090,  1911],
       [   46, 10009]], dtype=int64)

In [102]:
knn_ac1=knn_c1.diagonal().sum()/knn_c1.sum()*100
knn_ac1

90.24232149980055

In [103]:
print(classification_report(yte1,knn_p))

              precision    recall  f1-score   support

           0       0.99      0.81      0.89     10001
           1       0.84      1.00      0.91     10055

    accuracy                           0.90     20056
   macro avg       0.92      0.90      0.90     20056
weighted avg       0.92      0.90      0.90     20056



# XGB

In [104]:
xgb.fit(xtr1,ytr1)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [105]:
xgb_p=xgb.predict(xte1)
#xgb_p

In [106]:
xgb_c=confusion_matrix(yte1,xgb_p)
xgb_c

array([[8098, 1903],
       [ 367, 9688]], dtype=int64)

In [107]:
xgb_ac=xgb_c.diagonal().sum()/xgb_c.sum()*100
xgb_ac

88.68169126445952

In [108]:
print(classification_report(yte1,xgb_p))

              precision    recall  f1-score   support

           0       0.96      0.81      0.88     10001
           1       0.84      0.96      0.90     10055

    accuracy                           0.89     20056
   macro avg       0.90      0.89      0.89     20056
weighted avg       0.90      0.89      0.89     20056



# Navie Bayes

In [109]:
nb.fit(xtr1,ytr1)

MultinomialNB()

In [110]:
nb_p=nb.predict(xte1)

In [111]:
nb_cf=confusion_matrix(yte1,nb_p)
nb_cf

array([[6268, 3733],
       [3533, 6522]], dtype=int64)

In [112]:
nb_acc=nb_cf.diagonal().sum()/nb_cf.sum()*100
nb_acc

63.77143996808935

In [113]:
print(classification_report(yte1,nb_p))

              precision    recall  f1-score   support

           0       0.64      0.63      0.63     10001
           1       0.64      0.65      0.64     10055

    accuracy                           0.64     20056
   macro avg       0.64      0.64      0.64     20056
weighted avg       0.64      0.64      0.64     20056



# SVM

In [114]:
#svm.fit(xtr1,ytr1)

In [115]:
#svm_p=svm.predict(xte1)

In [116]:
#svm_cf=confusion_matrix(yte1,svm_p)
#svm_cf

In [117]:
#svm_ac=svm_cf.diagonal().sum()/svm_cf.sum()*100
#svm_ac

In [118]:
#print(classification_report(yte1,svm_p))

In [119]:
#Conclusion: Rf=98% accuracy which overfitted so we have to do feature selection after that #we have to do RF then we get correct accuracy.

# IMBLEARN - UnderSampling

In [120]:
import imblearn

In [121]:
from imblearn.under_sampling import RandomUnderSampler

In [122]:
data_train.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [123]:
d_x=data_train.iloc[:,0:-1]
d_y=data_train.iloc[:,-1]

In [124]:
a1=RandomUnderSampler(sampling_strategy="all")

In [125]:
x1,y1=a1.fit_resample(d_x,d_y)

In [126]:
x1.shape,y1.shape

((9336, 12), (9336,))

In [127]:
from sklearn.model_selection import train_test_split
xtr2,xte2,ytr2,yte2=train_test_split(x1,y1,test_size=0.2,random_state=100)

In [128]:
#LG

# Decision Tree

In [129]:
dt.fit(xtr2,ytr2)

DecisionTreeClassifier()

In [130]:
dt_p=dt.predict(xte2)
dt_p

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [131]:
dt_c=confusion_matrix(yte2,dt_p)
dt_c

array([[729, 212],
       [218, 709]], dtype=int64)

In [132]:
c=confusion_matrix(yte2,dt_p)

In [133]:
dt_ac=c.diagonal().sum()/dt_c.sum()*100
dt_ac

76.98072805139186

In [134]:
print(classification_report(yte2,dt_p))

              precision    recall  f1-score   support

           0       0.77      0.77      0.77       941
           1       0.77      0.76      0.77       927

    accuracy                           0.77      1868
   macro avg       0.77      0.77      0.77      1868
weighted avg       0.77      0.77      0.77      1868



# RF

In [135]:
rf.fit(xtr2,ytr2)

RandomForestClassifier()

In [136]:
rf_p=rf.predict(xte2)

In [137]:
rf_c=confusion_matrix(yte2,rf_p)
rf_c

array([[698, 243],
       [108, 819]], dtype=int64)

In [138]:
rf_ac=rf_c.diagonal().sum()/rf_c.sum()*100
rf_ac

81.20985010706639

In [139]:
print(classification_report(yte2,rf_p))

              precision    recall  f1-score   support

           0       0.87      0.74      0.80       941
           1       0.77      0.88      0.82       927

    accuracy                           0.81      1868
   macro avg       0.82      0.81      0.81      1868
weighted avg       0.82      0.81      0.81      1868



# XGB

In [140]:
xgb.fit(xtr2,ytr2)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [141]:
xgb_p=xgb.predict(xte2)

In [142]:
xgb_c=confusion_matrix(yte2,xgb_p)
xgb_c

array([[727, 214],
       [128, 799]], dtype=int64)

In [143]:
xgb_ac=xgb_c.diagonal().sum()/xgb_c.sum()*100
xgb_ac

81.6916488222698

In [144]:
print(classification_report(yte2,xgb_p))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       941
           1       0.79      0.86      0.82       927

    accuracy                           0.82      1868
   macro avg       0.82      0.82      0.82      1868
weighted avg       0.82      0.82      0.82      1868



# IMBLearn Oversampling

In [145]:
x7=data_train.iloc[:,0:-1]
y7=data_train.iloc[:,-1]

In [146]:
from imblearn.over_sampling import RandomOverSampler

In [148]:
a1=RandomOverSampler(random_state=42)
x8,y8=a1.fit_resample(x7,y7)

In [149]:
x8.shape

(100280, 12)

In [150]:
y8.shape

(100280,)

In [151]:
x8.shape,y8.shape

((100280, 12), (100280,))

In [155]:
x8_tr,x8_te,y8_tr,y8_te=train_test_split(x8,y8,test_size=0.2,random_state=100)
x8_tr.shape,x8_te.shape,y8_tr.shape,y8_te.shape

((80224, 12), (20056, 12), (80224,), (20056,))

In [156]:
#logistic regression
lg.fit(x8_tr,y8_tr)

LogisticRegression()

In [157]:
p8=lg.predict(x8_te)

In [158]:
cf8=confusion_matrix(y8_te,p8)
cf8

array([[7167, 2859],
       [2635, 7395]], dtype=int64)

In [159]:
acc8=cf8.diagonal().sum()/cf8.sum()*100
acc8

72.6067012365377

In [160]:
print(classification_report(y8_te,p8))

              precision    recall  f1-score   support

           0       0.73      0.71      0.72     10026
           1       0.72      0.74      0.73     10030

    accuracy                           0.73     20056
   macro avg       0.73      0.73      0.73     20056
weighted avg       0.73      0.73      0.73     20056



In [161]:
#DT
dt.fit(x8_tr,y8_tr)

DecisionTreeClassifier()

In [162]:
dt_p8=dt.predict(x8_te)

In [163]:
dt_cf8=confusion_matrix(y8_te,dt_p8)
dt_cf8

array([[ 9420,   606],
       [    0, 10030]], dtype=int64)

In [164]:
dt_acc8=dt_cf8.diagonal().sum()/dt_cf8.sum()*100
dt_acc8

96.97846031112884

In [165]:
print(classification_report(y8_te,dt_p8))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97     10026
           1       0.94      1.00      0.97     10030

    accuracy                           0.97     20056
   macro avg       0.97      0.97      0.97     20056
weighted avg       0.97      0.97      0.97     20056



In [166]:
#RF
rf.fit(x8_tr,y8_tr)

RandomForestClassifier()

In [168]:
rf_p8=rf.predict(x8_te)

In [169]:
rf_cf8=confusion_matrix(y8_te,rf_p8)
rf_cf8

array([[ 9771,   255],
       [    0, 10030]], dtype=int64)

In [170]:
rf_acc8=rf_cf8.diagonal().sum()/rf_cf8.sum()*100
rf_acc8

98.72856003191065

In [171]:
print(classification_report(y8_te,rf_p8))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99     10026
           1       0.98      1.00      0.99     10030

    accuracy                           0.99     20056
   macro avg       0.99      0.99      0.99     20056
weighted avg       0.99      0.99      0.99     20056



In [172]:
#xgb
xgb.fit(x8_tr,y8_tr)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [173]:
xgb_p8=xgb.predict(x8_te)

In [175]:
xgb_cf8=confusion_matrix(y8_te,xgb_p8)
xgb_cf8

array([[8178, 1848],
       [ 396, 9634]], dtype=int64)

In [176]:
xgb_acc8=xgb_cf8.diagonal().sum()/xgb_cf8.sum()*100
xgb_acc8

88.81132828081371

In [178]:
print(classification_report(y8_te,xgb_p8))

              precision    recall  f1-score   support

           0       0.95      0.82      0.88     10026
           1       0.84      0.96      0.90     10030

    accuracy                           0.89     20056
   macro avg       0.90      0.89      0.89     20056
weighted avg       0.90      0.89      0.89     20056



# SVM,KNN, Naive Bayes-IMBLearn - Oversampling

# SMOTE

In [179]:
#Synthetic Minority Oversampling Techniques-Full form of SMOTE 

In [181]:
hr_x=data_train.iloc[:,0:-1]
hr_y=data_train.iloc[:,-1]

In [182]:
hr_y.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [185]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()

In [186]:
x_smote,y_smote=smote.fit_resample(hr_x,hr_y)

In [187]:
x_smote.shape,y_smote.shape

((100280, 12), (100280,))

In [188]:
y_smote.value_counts()

0    50140
1    50140
Name: is_promoted, dtype: int64

In [214]:
xtr9,xte9,ytr9,yte9=train_test_split(x_smote,y_smote,test_size=0.2,random_state=100)
xtr9.shape,xte9.shape,ytr9.shape,yte9.shape

((80224, 12), (20056, 12), (80224,), (20056,))

In [215]:
#logistic regression
lg.fit(xtr9,ytr9)

LogisticRegression()

In [216]:
p9=lg.predict(xte9)

In [217]:
cf9=confusion_matrix(yte9,p9)
cf9

array([[7067, 2959],
       [2683, 7347]], dtype=int64)

In [218]:
acc9=cf9.diagonal().sum()/cf9.sum()*100
acc9

71.86876745113682

In [219]:
print(classification_report(yte9,p9))

              precision    recall  f1-score   support

           0       0.72      0.70      0.71     10026
           1       0.71      0.73      0.72     10030

    accuracy                           0.72     20056
   macro avg       0.72      0.72      0.72     20056
weighted avg       0.72      0.72      0.72     20056



In [220]:
#DT
dt.fit(xtr9,ytr9)

DecisionTreeClassifier()

In [221]:
dt_p9=dt.predict(xte9)

In [222]:
dt_cf9=confusion_matrix(yte9,dt_p9)
dt_cf9

array([[9128,  898],
       [ 542, 9488]], dtype=int64)

In [223]:
dt_acc9=dt_cf9.diagonal().sum()/dt_cf9.sum()*100
dt_acc9

92.8201037096131

In [224]:
print(classification_report(yte9,dt_p9))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93     10026
           1       0.91      0.95      0.93     10030

    accuracy                           0.93     20056
   macro avg       0.93      0.93      0.93     20056
weighted avg       0.93      0.93      0.93     20056



In [225]:
#RF
rf.fit(xtr9,ytr9)

RandomForestClassifier()

In [226]:
rf_p9=rf.predict(xte9)

In [227]:
rf_cf9=confusion_matrix(yte9,rf_p9)
rf_cf9

array([[9565,  461],
       [ 475, 9555]], dtype=int64)

In [228]:
rf_acc9=rf_cf9.diagonal().sum()/rf_cf9.sum()*100
rf_acc9

95.3330674112485

In [229]:
print(classification_report(yte9,rf_p9))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95     10026
           1       0.95      0.95      0.95     10030

    accuracy                           0.95     20056
   macro avg       0.95      0.95      0.95     20056
weighted avg       0.95      0.95      0.95     20056



In [230]:
#xgb
xgb.fit(xtr9,ytr9)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [231]:
xgb_p9=xgb.predict(xte9)

In [232]:
xgb_cf9=confusion_matrix(yte9,xgb_p9)
xgb_cf9

array([[9300,  726],
       [ 936, 9094]], dtype=int64)

In [233]:
xgb_acc9=xgb_cf9.diagonal().sum()/xgb_cf9.sum()*100
xgb_acc9

91.71320303151177

In [234]:
print(classification_report(yte9,xgb_p9))

              precision    recall  f1-score   support

           0       0.91      0.93      0.92     10026
           1       0.93      0.91      0.92     10030

    accuracy                           0.92     20056
   macro avg       0.92      0.92      0.92     20056
weighted avg       0.92      0.92      0.92     20056



# NEARMISS

In [235]:
from imblearn.under_sampling import NearMiss
nm=NearMiss()

In [212]:
x_nm,y_nm=nm.fit_resample(hr_x,hr_y)

In [236]:
x_nm.shape,y_nm.shape

((9336, 12), (9336,))

In [238]:
xtr10,xte10,ytr10,yte10=train_test_split(x_nm,y_nm,test_size=0.2,random_state=100)
xtr10.shape,xte10.shape,xtr10.shape,yte10.shape

((7468, 12), (1868, 12), (7468,), (1868,))

In [240]:
#Logistic Reg
lg.fit(xtr10,ytr10)
lg_p10=lg.predict(xte10)
lg_cf10=confusion_matrix(yte10,lg_p10)
lg_cf10

LogisticRegression()

In [245]:
lg_acc10=lg_cf10.diagonal().sum()/lg_cf10.sum()*100
lg_acc10
print(classification_report(yte10,lg_p10))

              precision    recall  f1-score   support

           0       0.65      0.76      0.70       941
           1       0.71      0.59      0.64       927

    accuracy                           0.68      1868
   macro avg       0.68      0.68      0.67      1868
weighted avg       0.68      0.68      0.67      1868



In [246]:
#Dt
dt.fit(xtr10,ytr10)
dt_p10=dt.predict(xte10)
dt_cf10=confusion_matrix(yte10,dt_p10)
dt_cf10

array([[688, 253],
       [252, 675]], dtype=int64)

In [248]:
dt_acc10=dt_cf10.diagonal().sum()/dt_cf10.sum()*100
dt_acc10
print(classification_report(yte10,dt_p10))

              precision    recall  f1-score   support

           0       0.73      0.73      0.73       941
           1       0.73      0.73      0.73       927

    accuracy                           0.73      1868
   macro avg       0.73      0.73      0.73      1868
weighted avg       0.73      0.73      0.73      1868



In [250]:
#RF
rf.fit(xtr10,ytr10)
rf_p10=rf.predict(xte10)
rf_cf10=confusion_matrix(yte10,rf_p10)
rf_cf10

array([[767, 174],
       [232, 695]], dtype=int64)

In [251]:
rf_acc10=lg_cf10.diagonal().sum()/rf_cf10.sum()*100
rf_acc10
print(classification_report(yte10,rf_p10))

              precision    recall  f1-score   support

           0       0.77      0.82      0.79       941
           1       0.80      0.75      0.77       927

    accuracy                           0.78      1868
   macro avg       0.78      0.78      0.78      1868
weighted avg       0.78      0.78      0.78      1868



In [255]:
#XGB
xgb.fit(xtr10,ytr10)
xgb_p10=xgb.predict(xte10)
xgb_cf10=confusion_matrix(yte10,xgb_p10)
xgb_cf10

array([[816, 125],
       [206, 721]], dtype=int64)

In [256]:
xgb_acc10=xgb_cf10.diagonal().sum()/xgb_cf10.sum()*100
xgb_acc10
print(classification_report(yte10,xgb_p10))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       941
           1       0.85      0.78      0.81       927

    accuracy                           0.82      1868
   macro avg       0.83      0.82      0.82      1868
weighted avg       0.83      0.82      0.82      1868



In [257]:
#SVM,KNN,Naive Bayes